/**
 * @fileoverview gRPC-Web generated client stub for gangWars
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.3
// source: farm.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.gangWars = require('./farm_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.gangWars.FarmServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.gangWars.FarmServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.gangWars.StartRequest,
 *   !proto.gangWars.StartResponse>}
 */
const methodDescriptor_FarmService_Start = new grpc.web.MethodDescriptor(
  '/gangWars.FarmService/Start',
  grpc.web.MethodType.UNARY,
  proto.gangWars.StartRequest,
  proto.gangWars.StartResponse,
  /**
   * @param {!proto.gangWars.StartRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.gangWars.StartResponse.deserializeBinary
);


/**
 * @param {!proto.gangWars.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.gangWars.StartResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.gangWars.StartResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.gangWars.FarmServiceClient.prototype.start =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/gangWars.FarmService/Start',
      request,
      metadata || {},
      methodDescriptor_FarmService_Start,
      callback);
};


/**
 * @param {!proto.gangWars.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.gangWars.StartResponse>}
 *     Promise that resolves to the response
 */
proto.gangWars.FarmServicePromiseClient.prototype.start =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/gangWars.FarmService/Start',
      request,
      metadata || {},
      methodDescriptor_FarmService_Start);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.gangWars.CollectRequest,
 *   !proto.gangWars.CollectResponse>}
 */
const methodDescriptor_FarmService_Collect = new grpc.web.MethodDescriptor(
  '/gangWars.FarmService/Collect',
  grpc.web.MethodType.UNARY,
  proto.gangWars.CollectRequest,
  proto.gangWars.CollectResponse,
  /**
   * @param {!proto.gangWars.CollectRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.gangWars.CollectResponse.deserializeBinary
);


/**
 * @param {!proto.gangWars.CollectRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.gangWars.CollectResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.gangWars.CollectResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.gangWars.FarmServiceClient.prototype.collect =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/gangWars.FarmService/Collect',
      request,
      metadata || {},
      methodDescriptor_FarmService_Collect,
      callback);
};


/**
 * @param {!proto.gangWars.CollectRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.gangWars.CollectResponse>}
 *     Promise that resolves to the response
 */
proto.gangWars.FarmServicePromiseClient.prototype.collect =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/gangWars.FarmService/Collect',
      request,
      metadata || {},
      methodDescriptor_FarmService_Collect);
};


export default proto.gangWars;

